### PR TITLE
Responsive

### PR DESCRIPTION
**Pull request by DJOcean**

### CODE REVIEW

**Comment by theWickedWebDev** [comment]
cant you attach screen shots please?

**Comment by theWickedWebDev** [comment]
and explain what is happening so I can visualize it

**Comment by DJOcean** [comment]
the narrow ones are what they look like on mobile and the wider ones are the midway inbetween that you will see on ipads and such

**Comment by theWickedWebDev** [comment]
delete them from the branch and re-commit  (post a few of them here tho as comments)

**Comment by theWickedWebDev** [comment]
also, make the text "What my clients say..." fit on one line

**Comment by theWickedWebDev** [comment]
looking good though!

**Comment by DJOcean** [comment]
screenshot from 2015-02-10 20 51 01
screenshot from 2015-02-10 20 48 39
screenshot from 2015-02-10 20 47 59

**Comment by theWickedWebDev** [comment]
LGTM

**Pull request merged**
